### ISSUE TITLE
PlatformNotSupportedException is raised when access PinValue

### ISSUE THREAD

**Issue by maxim-tkachenko** [dotnet/iot#687]
I'm getting PlatformNotSupportedException when access PinValue:
`var value = PinValue.High;`

`System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Device.Gpio.PinValue.get_High()`
Why does it happen? `PinValue` doesn't have anything platform specific. I'm running the code on Mac.

**Comment by maxim-tkachenko** [comment]
hi @joperezr, thanks for the answer, didn't know about the tool for mac. Yes, I have a dev environment on mac but run on the raspberry. I've mocked GpioController for debug builds, but since another base library types (like PinValue) doesn't implement any specific interfaces, there is no way to do it. The only way currently I see is to create some adapter class which will work with all library specific types. Is it possible do not throw the not supported exception for the common types of all platforms? Maybe I'm not the only one who develop on the mac :)

**Comment by maxim-tkachenko** [comment]
unfortunately, operator overloads throw the same PlatformNotSupportedException

**Comment by maxim-tkachenko** [comment]
yeah, that's what I meant when was writing about adapter class. And it's only way currently I see to achieve my needs.

**Comment by DavidKarlas** [comment]
I ran into same problem today, with `GpioDriver` constructor...
If you don't care about what happens on macOs, why did you make tool that injects exceptions?

My use case is... I want to write custom GpioDriver that talks with Arduino(with custom .ino) over serial and expose Arduino pins, so I can do whole logic in C# on Mac/Linux/Windows...

**Comment by DavidKarlas** [comment]
For anyone who also runs into this issue, do `cp ~/.nuget/packages/system.device.gpio/1.0.0/runtimes/linux/lib/netstandard2.0/* ~/.nuget/packages/system.device.gpio/1.0.0/lib/netstandard2.0/` as workaround and rebuild your project.

**Comment by pgrawehr** [comment]
@joperezr Maybe we could include a simulation implementation instead of the NotSupported implementation? In a first version, this would probably just act as a Null device, but could be extended up to something that reads diagrams and simulates them.

**Comment by madameczek** [comment]
I faced PlatformNotSupportedException as well. Target linux-arm platform Raspberry Pi 4 (Raspbian buster), .NET Core on Pi 3.1.301.
Firstly on OpenPin(). 
Then replaced System.Device.Gpio 1.0.0 to 1.1.0-prerelease.20276.1.
Now the exception is thrown on creating GpioController. It is detected by debugger, but doesn't fall into catch statement.
A pin can be opened and written, at least.

**Comment by Ellerbach** [comment]
@madameczek this is related to latest RPI4 raspbian update. This has been fixed few days ago. 
Please use the lastest should be 20508.1 and that should solve your issue.

**Comment by madameczek** [comment]
Thx for info. After OS upgrade, issue is solved.

**Comment by Ellerbach** [comment]
Great, thanks @madameczek, so closing the issue!

**Comment by DavidKarlas** [comment]
@Ellerbach Original bug is about exception on Mac which is not fixed as far as I understand

**Comment by Ellerbach** [comment]
@DavidKarlas so reopening it!

**Comment by pgrawehr** [comment]
@Ellerbach : I have no mac, so I cannot verify,  but I do believe the issue is solved with the removal of the platform dependent assemblies. The main problem was that for any unsupported OS, an assembly was used that consisted only of PNSE. 
Applications such as the one mentioned above,  with an Arduino on Mac or Windows are possible now (PR pending)

**Comment by joperezr** [comment]
What @pgrawehr says above is correct. The PNSE issue has been fixed post 1.0 when we removed platform specific implementations. Closing again 😄
